services:
  # task-scheduler:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: task-scheduler
  #   # Aumenta i limiti di memoria per il container
  #   mem_limit: 4g
  #   memswap_limit: 2g
  #   volumes:
  #     - ./src:/app/src
  #     - ./logs:/app/logs
  #     - ./data:/app/data
  #     - ~/.ssh/id_rsa:/app/ssh_key:ro
  #   env_file:
  #     - .env
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - LOG_LEVEL=INFO
  #   stdin_open: true
  #   tty: true
  #   restart: unless-stopped
  #   networks:
  #     - scip-network

  task-scheduler-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-scheduler-api
    command: python -m src.run_api --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    # Aumenta i limiti di memoria per il container
    mem_limit: 4g
    memswap_limit: 2g
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./data:/app/data
      - ~/.ssh/id_rsa:/app/ssh_key:ro
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - scip-network

networks:
  scip-network:
    driver: bridge

volumes:
  postgres_data: